FROM images.home.mtaylor.io/haskell:latest
# Install system dependencies
USER root
RUN apt-get update && apt-get install -y libpq-dev zlib1g-dev \
  && apt-get clean && rm -rf /var/lib/apt/lists/*
# Add metadata files and build dependencies
USER build
ADD --chown=build:build . .
RUN stack build --system-ghc --copy-bins
