name:                mtaylor-io-events-server
version:             0.1.54
github:              "mtaylorio/events-server"
license:             BSD-3-Clause
author:              "Mike Taylor"
maintainer:          "mike.charles.taylor@gmail.com"
copyright:           "Copyright (c) 2024"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mtaylorio/events-server#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- base64
- bytestring
- containers
- ed25519
- hasql
- hasql-migration
- hasql-pool >= 0.9 && < 0.10
- hasql-transaction
- http-client
- http-client-tls
- http-types
- lens
- mtaylor-io-events-core
- mtaylor-io-iam-client
- mtaylor-io-iam-core
- mtl
- network
- optparse-applicative
- servant-client
- servant-server
- stm
- text
- time
- unix
- uuid
- wai
- wai-extra
- wai-websockets
- warp
- websockets

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  events-mtaylor-io:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtaylor-io-events-server

tests:
  events-mtaylor-io-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtaylor-io-events-server
